id: A7FD90DEB
title: 'A Shower of Blessings: A Guru Yoga Practice to Accompany the Seven Line Prayer
  (Addendum)'
type: translation
source_metadata:
  languages:
  - en
  - zh
  - bo
  datatype: PlainText
  created_at: 2022-03-01 05:45:59.201821
  last_modified_at: 2022-03-01 05:45:59.201833
