id: A7FD90DEB
title: Remainder Torma Offering for Seven-Line Prayer Guru Yoga
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 05:45:59.209059
  last_modified_at: 2022-03-01 05:45:59.209070
